// Builds src/data/brief.json: a short written summary of the current insider
// feed, generated by Gemini once a day and committed.
//
// Page views read the committed file, so traffic never costs an LLM call and
// the free-tier quota can't be exhausted by visitors.
//
//   GEMINI_API_KEY=xxxx npm run brief
import { writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { getInsiderReport } from "../src/lib/openinsider";
import { writeBrief, looksComplete, type BriefFile } from "../src/lib/brief";

const KEY = process.env.GEMINI_API_KEY;
if (!KEY) {
  console.error("Missing GEMINI_API_KEY.");
  console.error("Get a free key at https://aistudio.google.com/apikey");
  process.exit(1);
}

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/data/brief.json");

// Below this the feed is too thin to say anything meaningful about, and a brief
// written from three rows reads worse than no brief at all.
const MIN_ROWS = 6;

function keepExisting(why: string): never {
  console.error(`\n${why}`);
  if (existsSync(OUT)) {
    console.error("src/data/brief.json is untouched; the page keeps the last good brief.\n");
    process.exit(0); // not a failure — yesterday's brief is still valid
  }
  console.error("No existing brief to fall back on; the page will render without one.\n");
  process.exit(0);
}

async function main() {
  const report = await getInsiderReport();
  const rows = report.clusterBuys.length + report.bigBuys.length;
  console.log(`feed: ${report.clusterBuys.length} cluster, ${report.bigBuys.length} notable`);

  if (rows < MIN_ROWS) keepExisting(`Only ${rows} rows — too thin to summarise.`);

  const brief = await writeBrief(report.clusterBuys, report.bigBuys, KEY!);
  console.log(`\n${brief.text}\n`);

  // A truncated or degenerate generation must never replace a good brief.
  if (brief.text.length < 80) keepExisting(`Generated text is only ${brief.text.length} chars.`);
  if (!looksComplete(brief.text)) keepExisting("Generated text ends mid-sentence (truncated).");

  const file: BriefFile = { brief };
  writeFileSync(OUT, `${JSON.stringify(file, null, 2)}\n`);
  console.log(`wrote ${OUT}`);
}

main().catch((err) => {
  // Never fail the pipeline over the brief: it's an enhancement, and the
  // insider tables are the actual product. A stale paragraph beats a red build.
  keepExisting(`Brief generation failed: ${(err as Error).message}`);
});
